# 📚 Document Question Answering System (RAG)
### Week 7 — Umang Vijay | JECRC University
### Celebal CEI Data Science Internship

---

## 🎯 Project Overview
This notebook implements a **Retrieval-Augmented Generation (RAG)** system that answers questions from custom documents.
Instead of relying only on a language model's internal knowledge, the system **retrieves** relevant information from documents
and then **generates** answers grounded in that information.

### Pipeline Architecture
```
📄 Documents → 🔪 Chunking → 🧮 Embeddings → 🗄️ Vector DB → 🔍 Retrieval → 🤖 Generation → 💬 Answer
```

### Key Components
| Component | Tool | Purpose |
|-----------|------|---------|
| Embedding Model | `sentence-transformers/all-MiniLM-L6-v2` | Convert text to 384-dim vectors |
| Vector Store | FAISS (Facebook AI Similarity Search) | Fast similarity search |
| Language Model | `google/flan-t5-base` | Answer generation |
| Re-ranker | `cross-encoder/ms-marco-MiniLM-L-6-v2` | Re-rank retrieved results |
| Dataset | `vectara/open_ragbench` + Custom PDFs/TXT | Document sources |

## Objectives
* Understand the concept of Retrieval-Augmented Generation (RAG)
* Build a pipeline combining retrieval and generation
* Enable question answering over custom documents such as PDFs or text files
* Learn how modern AI systems work internally

## Key Concepts
### 1. Retrieval
Retrieval is responsible for finding the most relevant chunks of text from a document. 
It typically uses embeddings and vector similarity search.
### 2. Augmentation
The retrieved content is added to the model's input to provide context for answering.
### 3. Generation
A language model generates the final answer using the retrieved context, 
ensuring responses are grounded in actual data.

## System Architecture
The pipeline consists of the following stages:
1. **Document Ingestion** - Documents (PDFs/text files) are loaded and converted into raw text
2. **Text Chunking** - Text is split into smaller chunks to improve retrieval accuracy
3. **Embedding Creation** - Each chunk is converted into a vector representation
4. **Vector Database** - Embeddings are stored for efficient similarity search
5. **Query Processing** - The user's question is converted into an embedding
6. **Context Retrieval** - Most relevant chunks are retrieved from the database
7. **Answer Generation** - A language model generates an answer using the retrieved context

### Data Sources
* PDF documents
* Text files
* Notes or articles
* HuggingFace datasets (e.g., `vectara/open_ragbench`)

### Workflow
```
Load Documents -> Split into Chunks -> Create Embeddings -> Store in Vector DB
     -> Accept Query -> Retrieve Relevant Chunks -> Generate Answer
```

## 📦 Section 1: Environment Setup & Dependencies

In [20]:
# Install all required packages
!pip install -q sentence-transformers faiss-cpu transformers torch datasets \
    PyPDF2 gradio rank-bm25 pandas numpy tqdm ipywidgets plotly

## 📥 Section 2: Import Libraries

In [21]:
import os, re, time, json, warnings, textwrap
import numpy as np
import pandas as pd
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from pathlib import Path

# NLP & ML
import torch
from sentence_transformers import SentenceTransformer, CrossEncoder
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
import faiss

# Data
from datasets import load_dataset
from rank_bm25 import BM25Okapi

# Visualization
import plotly.graph_objects as go
import plotly.express as px
from IPython.display import display, HTML, Markdown

warnings.filterwarnings('ignore')
print('✅ All libraries imported successfully!')
print(f'🔧 PyTorch device: {"cuda" if torch.cuda.is_available() else "cpu"}')

✅ All libraries imported successfully!
🔧 PyTorch device: cpu

## 📄 Section 3: Document Ingestion Module
**Intern Instruction #1**: Build a document ingestion module that accepts custom text inputs
such as PDFs, raw text files, or domain-specific Hugging Face archives.

In [22]:
@dataclass
class Document:
    """Represents an ingested document with metadata."""
    content: str
    source: str
    doc_type: str
    metadata: dict = field(default_factory=dict)


class DocumentIngester:
    """Multi-format document ingestion module.
    Supports: PDF, TXT, raw text strings, and HuggingFace datasets.
    """

    def __init__(self):
        self.documents: List[Document] = []
        self.ingestion_log = []

    def ingest_text(self, text: str, source: str = 'raw_input') -> Document:
        """Ingest raw text string."""
        doc = Document(content=text.strip(), source=source, doc_type='text')
        self.documents.append(doc)
        self._log('text', source, len(text))
        return doc

    def ingest_txt_file(self, filepath: str) -> Document:
        """Ingest a .txt file."""
        path = Path(filepath)
        if not path.exists():
            raise FileNotFoundError(f'File not found: {filepath}')
        content = path.read_text(encoding='utf-8', errors='ignore')
        doc = Document(content=content, source=str(path.name),
                       doc_type='txt', metadata={'path': str(path)})
        self.documents.append(doc)
        self._log('txt', str(path.name), len(content))
        return doc

    def ingest_pdf(self, filepath: str) -> Document:
        """Ingest a PDF file using PyPDF2."""
        try:
            from PyPDF2 import PdfReader
        except ImportError:
            raise ImportError('PyPDF2 is required. Install: pip install PyPDF2')
        path = Path(filepath)
        if not path.exists():
            raise FileNotFoundError(f'PDF not found: {filepath}')
        reader = PdfReader(str(path))
        pages = []
        for i, page in enumerate(reader.pages):
            text = page.extract_text() or ''
            pages.append(text)
        content = '\n\n'.join(pages)
        doc = Document(content=content, source=str(path.name),
                       doc_type='pdf',
                       metadata={'path': str(path), 'num_pages': len(pages)})
        self.documents.append(doc)
        self._log('pdf', str(path.name), len(content), extra=f'{len(pages)} pages')
        return doc

    def ingest_huggingface(self, dataset_name: str, text_field: str,
                           split: str = 'train', max_docs: int = 50) -> List[Document]:
        """Ingest documents from a HuggingFace dataset."""
        ds = load_dataset(dataset_name, split=split, streaming=True)
        docs = []
        for i, item in enumerate(ds):
            if i >= max_docs:
                break
            text = str(item.get(text_field, ''))
            if len(text.strip()) < 20:
                continue
            doc = Document(content=text, source=f'{dataset_name}[{i}]',
                           doc_type='huggingface',
                           metadata={'dataset': dataset_name, 'index': i})
            self.documents.append(doc)
            docs.append(doc)
        self._log('huggingface', dataset_name, sum(len(d.content) for d in docs),
                  extra=f'{len(docs)} docs')
        return docs

    def _log(self, dtype, source, chars, extra=''):
        entry = {'type': dtype, 'source': source, 'characters': chars,
                 'extra': extra, 'timestamp': time.strftime('%H:%M:%S')}
        self.ingestion_log.append(entry)
        print(f'  ✅ Ingested [{dtype.upper()}] {source} — {chars:,} chars {extra}')

    def get_summary(self) -> pd.DataFrame:
        return pd.DataFrame(self.ingestion_log)


ingester = DocumentIngester()
print('✅ Document Ingestion Module ready!')

✅ Document Ingestion Module ready!

### 3.1 — Ingest Sample Documents
We'll ingest multiple document types to demonstrate the pipeline.

In [23]:
# ─── 1) Ingest raw text: AI & Machine Learning overview ───
ai_text = """
Artificial Intelligence (AI) refers to the simulation of human intelligence in machines
that are programmed to think and learn like humans. The term may also be applied to any
machine that exhibits traits associated with a human mind such as learning and problem-solving.

Machine Learning is a subset of AI that provides systems the ability to automatically learn
and improve from experience without being explicitly programmed. It focuses on the development
of computer programs that can access data and use it to learn for themselves.

Deep Learning is part of a broader family of machine learning methods based on artificial
neural networks with representation learning. Learning can be supervised, semi-supervised
or unsupervised. Deep learning architectures such as deep neural networks, recurrent neural
networks, convolutional neural networks and transformers have been applied to fields including
computer vision, speech recognition, natural language processing, and machine translation.

Natural Language Processing (NLP) is a subfield of linguistics, computer science, and
artificial intelligence concerned with the interactions between computers and human language.
NLP involves the application of computational techniques to the analysis and synthesis of
natural language and speech. Key tasks include text classification, named entity recognition,
sentiment analysis, machine translation, question answering, and text summarization.

Retrieval-Augmented Generation (RAG) is a technique that combines information retrieval
with text generation. In a RAG system, when a user asks a question, the system first
retrieves relevant documents or passages from a knowledge base, then uses a language model
to generate an answer based on the retrieved context. This approach helps reduce hallucinations
and provides more accurate, up-to-date answers compared to purely generative models.

Vector databases are specialized databases designed to store and query high-dimensional vectors.
They are essential for semantic search and RAG systems. Popular vector databases include
FAISS, Pinecone, Weaviate, Milvus, and Chroma. These databases use approximate nearest
neighbor (ANN) algorithms for efficient similarity search across millions of vectors.

Transformer architecture, introduced in the paper 'Attention Is All You Need' by Vaswani
et al. in 2017, revolutionized NLP. Transformers use self-attention mechanisms to process
input sequences in parallel, unlike RNNs which process sequentially. Models like BERT, GPT,
T5, and their variants have achieved state-of-the-art results on numerous NLP benchmarks.

Transfer learning in NLP involves pre-training a model on a large corpus of text and then
fine-tuning it on a specific downstream task. This approach has dramatically improved
performance on tasks with limited labeled data. Pre-trained models like BERT and GPT capture
rich linguistic representations that transfer well across different NLP tasks.
"""
ingester.ingest_text(ai_text, source='AI_ML_Overview')

# ─── 2) Ingest raw text: RAG Systems deep dive ───
rag_text = """
Retrieval-Augmented Generation (RAG) Systems: A Comprehensive Guide

RAG systems represent a paradigm shift in how AI systems access and utilize knowledge.
Traditional language models rely solely on their parametric knowledge — information encoded
in model weights during training. RAG systems augment this with non-parametric knowledge
retrieved from external sources at inference time.

The RAG Pipeline consists of several key stages:

1. Document Ingestion: Raw documents (PDFs, web pages, databases) are collected and
   preprocessed. This involves text extraction, cleaning, and normalization.

2. Chunking: Documents are split into smaller, semantically meaningful chunks. Common
   strategies include fixed-size chunking, sentence-based chunking, and recursive
   character splitting. Chunk size and overlap are critical hyperparameters.

3. Embedding: Each chunk is converted into a dense vector representation using an
   embedding model. Popular models include sentence-transformers, OpenAI embeddings,
   and Cohere embeddings. The choice of embedding model affects retrieval quality.

4. Indexing: Embeddings are stored in a vector database for efficient similarity search.
   FAISS, Pinecone, and Chroma are popular choices. The index structure (flat, IVF, HNSW)
   affects search speed and accuracy.

5. Retrieval: When a query arrives, it is embedded using the same model, and the most
   similar chunks are retrieved from the vector database. Top-k retrieval is standard.

6. Re-ranking: Retrieved chunks can be re-ranked using a cross-encoder model for better
   relevance scoring. This two-stage approach (bi-encoder + cross-encoder) improves
   retrieval precision.

7. Generation: The retrieved context is combined with the original query in a prompt
   template, and a language model generates the final answer.

Advanced RAG Techniques:

- Hybrid Search: Combining dense vector search with sparse keyword search (BM25) for
  better coverage. This helps capture both semantic similarity and exact keyword matches.

- Query Expansion: Reformulating or expanding the original query to improve retrieval.
  Techniques include HyDE (Hypothetical Document Embeddings) and multi-query retrieval.

- Contextual Compression: Filtering and compressing retrieved documents to include only
  the most relevant information in the prompt.

- Evaluation Metrics: RAG systems are evaluated using metrics like retrieval precision,
  recall, NDCG for retrieval, and BLEU, ROUGE, BERTScore for generation quality.
  Faithfulness and relevance scores measure answer groundedness.
"""
ingester.ingest_text(rag_text, source='RAG_Deep_Dive')

# ─── 3) Ingest the Week7_Project.txt file if it exists ───
week7_path = r'd:\c++ homework\celebal cei data science internship assignments\Week7_Project.txt'
if os.path.exists(week7_path):
    ingester.ingest_txt_file(week7_path)
else:
    print('  ⚠️ Week7_Project.txt not found, skipping')

print(f'\n📊 Total documents ingested: {len(ingester.documents)}')
display(ingester.get_summary())

  ✅ Ingested [TEXT] AI_ML_Overview — 2,965 chars
  ✅ Ingested [TEXT] RAG_Deep_Dive — 2,584 chars

  ✅ Ingested [TXT] Week7_Project.txt — 3,829 chars

📊 Total documents ingested: 3

   type             source  characters extra timestamp
0  text     AI_ML_Overview        2965        12:01:16
1  text      RAG_Deep_Dive        2584        12:01:16
2   txt  Week7_Project.txt        3829        12:01:16

## 🔪 Section 4: Text Chunking Module
**Intern Instruction #2**: Process unstructured raw text by breaking it into smaller,
manageable chunks using a clean chunking methodology.

In [24]:
class TextChunker:
    """Advanced text chunking with multiple strategies."""

    def __init__(self, chunk_size=300, chunk_overlap=50):
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self.chunking_log = []

    def chunk_by_sentences(self, text: str, sentences_per_chunk: int = 5) -> List[str]:
        """Split text into chunks based on sentence boundaries."""
        sentences = re.split(r'(?<=[.!?])\s+', text.strip())
        sentences = [s.strip() for s in sentences if len(s.strip()) > 10]
        chunks = []
        for i in range(0, len(sentences), sentences_per_chunk - 1):
            chunk = ' '.join(sentences[i:i + sentences_per_chunk])
            if chunk.strip():
                chunks.append(chunk.strip())
        return chunks

    def chunk_by_characters(self, text: str) -> List[str]:
        """Fixed-size character chunking with overlap."""
        chunks = []
        start = 0
        while start < len(text):
            end = start + self.chunk_size
            chunk = text[start:end]
            # Try to break at a sentence or word boundary
            if end < len(text):
                last_period = chunk.rfind('.')
                last_space = chunk.rfind(' ')
                break_at = max(last_period, last_space)
                if break_at > self.chunk_size // 2:
                    chunk = chunk[:break_at + 1]
                    end = start + break_at + 1
            chunk = chunk.strip()
            if chunk:
                chunks.append(chunk)
            start = end - self.chunk_overlap
        return chunks

    def chunk_by_paragraphs(self, text: str) -> List[str]:
        """Split text by paragraph boundaries."""
        paragraphs = re.split(r'\n\s*\n', text)
        chunks = [p.strip() for p in paragraphs if len(p.strip()) > 30]
        return chunks

    def chunk_documents(self, documents: List[Document],
                        strategy: str = 'sentence') -> List[Dict]:
        """Chunk all documents and return chunk objects with metadata."""
        all_chunks = []
        for doc in documents:
            if strategy == 'sentence':
                texts = self.chunk_by_sentences(doc.content)
            elif strategy == 'character':
                texts = self.chunk_by_characters(doc.content)
            elif strategy == 'paragraph':
                texts = self.chunk_by_paragraphs(doc.content)
            else:
                texts = self.chunk_by_sentences(doc.content)

            for i, text in enumerate(texts):
                all_chunks.append({
                    'text': text,
                    'chunk_id': f'{doc.source}_chunk_{i}',
                    'source': doc.source,
                    'chunk_index': i,
                    'char_count': len(text),
                    'word_count': len(text.split())
                })

            self.chunking_log.append({
                'source': doc.source, 'strategy': strategy,
                'num_chunks': len(texts),
                'avg_chunk_size': int(np.mean([len(t) for t in texts])) if texts else 0
            })
        print(f'  ✅ Chunked {len(documents)} docs → {len(all_chunks)} chunks '
              f'(strategy={strategy})')
        return all_chunks


# Initialize and chunk documents
chunker = TextChunker(chunk_size=300, chunk_overlap=50)
chunks = chunker.chunk_documents(ingester.documents, strategy='sentence')

print(f'\n📊 Chunking Summary:')
display(pd.DataFrame(chunker.chunking_log))

# Show sample chunks
print(f'\n📝 Sample Chunk (first):')
print(textwrap.fill(chunks[0]['text'][:300], width=90))

  ✅ Chunked 3 docs → 20 chunks (strategy=sentence)

📊 Chunking Summary:

              source  strategy  num_chunks  avg_chunk_size
0     AI_ML_Overview  sentence           6             595
1      RAG_Deep_Dive  sentence           7             438
2  Week7_Project.txt  sentence           7             753

📝 Sample Chunk (first):
Artificial Intelligence (AI) refers to the simulation of human intelligence in machines
that are programmed to think and learn like humans. The term may also be applied to any
machine that exhibits traits associated with a human mind such as learning and problem-
solving. Machine Learning is a subset

## 🧮 Section 5: Embedding Creation
**Intern Instruction #3**: Map chunked text strings into equivalent vector representations
using a pre-trained embedding model.

We use `all-MiniLM-L6-v2` — a fast, efficient model producing 384-dimensional embeddings.

In [25]:
class EmbeddingEngine:
    """Handles text embedding using sentence-transformers."""

    def __init__(self, model_name='sentence-transformers/all-MiniLM-L6-v2'):
        print(f'  🔄 Loading embedding model: {model_name}')
        self.model = SentenceTransformer(model_name)
        self.model_name = model_name
        self.embedding_dim = self.model.get_sentence_embedding_dimension()
        print(f'  ✅ Model loaded! Embedding dimension: {self.embedding_dim}')

    def embed_texts(self, texts: List[str], batch_size: int = 32,
                    show_progress: bool = True) -> np.ndarray:
        """Convert list of texts to embedding vectors."""
        embeddings = self.model.encode(
            texts, batch_size=batch_size,
            show_progress_bar=show_progress,
            normalize_embeddings=True
        )
        return np.array(embeddings, dtype='float32')

    def embed_query(self, query: str) -> np.ndarray:
        """Embed a single query."""
        return self.model.encode([query], normalize_embeddings=True).astype('float32')


# Initialize and create embeddings
embed_engine = EmbeddingEngine()
chunk_texts = [c['text'] for c in chunks]

print(f'\n🔄 Embedding {len(chunk_texts)} chunks...')
start_time = time.time()
embeddings = embed_engine.embed_texts(chunk_texts)
embed_time = time.time() - start_time

print(f'\n✅ Embeddings created!')
print(f'  Shape: {embeddings.shape}')
print(f'  Time: {embed_time:.2f}s')
print(f'  Dimension: {embed_engine.embedding_dim}')

  🔄 Loading embedding model: sentence-transformers/all-MiniLM-L6-v2

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

  ✅ Model loaded! Embedding dimension: 384

🔄 Embedding 20 chunks...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Embeddings created!
  Shape: (20, 384)
  Time: 4.82s
  Dimension: 384

## 🗄️ Section 6: Vector Database (FAISS)
**Intern Instruction #4**: Initialize a vector database, store text embedding arrays,
and configure them for fast similarity matching.

In [26]:
class VectorStore:
    """FAISS-based vector store for similarity search."""

    def __init__(self, dimension: int, index_type: str = 'flatip'):
        self.dimension = dimension
        if index_type == 'flatip':
            self.index = faiss.IndexFlatIP(dimension)  # Inner product (cosine for normalized)
        elif index_type == 'flatl2':
            self.index = faiss.IndexFlatL2(dimension)
        else:
            self.index = faiss.IndexFlatIP(dimension)
        self.chunks = []
        self.index_type = index_type
        print(f'  ✅ FAISS index created: type={index_type}, dim={dimension}')

    def add(self, embeddings: np.ndarray, chunk_data: List[Dict]):
        """Add embeddings and associated chunk data to the store."""
        self.index.add(embeddings)
        self.chunks.extend(chunk_data)
        print(f'  ✅ Added {len(chunk_data)} vectors. Total: {self.index.ntotal}')

    def search(self, query_embedding: np.ndarray, top_k: int = 5) -> List[Dict]:
        """Search for most similar chunks."""
        scores, indices = self.index.search(query_embedding, top_k)
        results = []
        for score, idx in zip(scores[0], indices[0]):
            if idx < len(self.chunks):
                result = self.chunks[idx].copy()
                result['similarity_score'] = float(score)
                results.append(result)
        return results

    def get_stats(self) -> Dict:
        return {
            'total_vectors': self.index.ntotal,
            'dimension': self.dimension,
            'index_type': self.index_type
        }


# Initialize and populate vector store
vector_store = VectorStore(dimension=embed_engine.embedding_dim, index_type='flatip')
vector_store.add(embeddings, chunks)

print(f'\n📊 Vector Store Stats:')
for k, v in vector_store.get_stats().items():
    print(f'  {k}: {v}')

  ✅ FAISS index created: type=flatip, dim=384
  ✅ Added 20 vectors. Total: 20

📊 Vector Store Stats:
  total_vectors: 20
  dimension: 384
  index_type: flatip

## 🔍 Section 7: Query Processing & Retrieval Module
**Intern Instruction #5**: Create a user input route that converts questions into query vectors.

**Intern Instruction #6**: Build a retrieval module that queries the vector store to isolate
the most contextually relevant document chunks.

In [27]:
class HybridRetriever:
    """Hybrid retrieval combining vector search + BM25 keyword search + re-ranking."""

    def __init__(self, vector_store: VectorStore, embed_engine: EmbeddingEngine,
                 chunks: List[Dict], use_reranker: bool = True):
        self.vector_store = vector_store
        self.embed_engine = embed_engine
        self.chunks = chunks

        # BM25 for keyword search
        tokenized = [c['text'].lower().split() for c in chunks]
        self.bm25 = BM25Okapi(tokenized)

        # Cross-encoder for re-ranking
        self.reranker = None
        if use_reranker:
            print('  🔄 Loading re-ranker model...')
            self.reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
            print('  ✅ Re-ranker loaded!')

        self.retrieval_log = []

    def retrieve(self, query: str, top_k: int = 5,
                 method: str = 'hybrid', alpha: float = 0.7) -> List[Dict]:
        """Retrieve relevant chunks.
        Methods: 'vector', 'bm25', 'hybrid'
        alpha: weight for vector score in hybrid (1-alpha for BM25)
        """
        start = time.time()

        if method == 'vector':
            results = self._vector_search(query, top_k * 2)
        elif method == 'bm25':
            results = self._bm25_search(query, top_k * 2)
        else:  # hybrid
            results = self._hybrid_search(query, top_k * 2, alpha)

        # Re-rank if available
        if self.reranker and len(results) > 0:
            results = self._rerank(query, results, top_k)
        else:
            results = results[:top_k]

        elapsed = time.time() - start
        self.retrieval_log.append({
            'query': query[:60], 'method': method,
            'results': len(results), 'time_ms': round(elapsed * 1000, 1)
        })
        return results

    def _vector_search(self, query: str, top_k: int) -> List[Dict]:
        q_emb = self.embed_engine.embed_query(query)
        return self.vector_store.search(q_emb, top_k)

    def _bm25_search(self, query: str, top_k: int) -> List[Dict]:
        tokens = query.lower().split()
        scores = self.bm25.get_scores(tokens)
        top_indices = np.argsort(scores)[::-1][:top_k]
        results = []
        for idx in top_indices:
            if scores[idx] > 0:
                r = self.chunks[idx].copy()
                r['similarity_score'] = float(scores[idx])
                results.append(r)
        return results

    def _hybrid_search(self, query: str, top_k: int, alpha: float) -> List[Dict]:
        vec_results = self._vector_search(query, top_k)
        bm25_results = self._bm25_search(query, top_k)
        # Merge by reciprocal rank fusion
        score_map = {}
        for rank, r in enumerate(vec_results):
            cid = r['chunk_id']
            score_map[cid] = score_map.get(cid, {'chunk': r, 'score': 0})
            score_map[cid]['score'] += alpha * (1.0 / (rank + 1))
        for rank, r in enumerate(bm25_results):
            cid = r['chunk_id']
            score_map[cid] = score_map.get(cid, {'chunk': r, 'score': 0})
            score_map[cid]['score'] += (1 - alpha) * (1.0 / (rank + 1))
        merged = sorted(score_map.values(), key=lambda x: x['score'], reverse=True)
        results = []
        for item in merged[:top_k]:
            c = item['chunk'].copy()
            c['similarity_score'] = item['score']
            results.append(c)
        return results

    def _rerank(self, query: str, results: List[Dict], top_k: int) -> List[Dict]:
        pairs = [(query, r['text']) for r in results]
        scores = self.reranker.predict(pairs)
        for r, s in zip(results, scores):
            r['rerank_score'] = float(s)
        results.sort(key=lambda x: x['rerank_score'], reverse=True)
        return results[:top_k]


retriever = HybridRetriever(vector_store, embed_engine, chunks, use_reranker=True)
print('\n✅ Hybrid Retriever ready (Vector + BM25 + Cross-Encoder Re-ranking)!')

  🔄 Loading re-ranker model...

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

  ✅ Re-ranker loaded!

✅ Hybrid Retriever ready (Vector + BM25 + Cross-Encoder Re-ranking)!

## 🤖 Section 8: Answer Generation Module
**Intern Instruction #7**: Connect the retrieved context alongside the original query into
a unified language model prompt to extract a grounded response.

In [28]:
class AnswerGenerator:
    """Generates answers using a language model with retrieved context."""

    def __init__(self, model_name='google/flan-t5-base'):
        print(f'  🔄 Loading language model: {model_name}')
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
        self.model_name = model_name
        self.generation_log = []
        print(f'  ✅ Language model loaded!')

    def generate(self, query: str, context_chunks: List[Dict],
                 max_length: int = 256) -> Dict:
        """Generate an answer using retrieved context."""
        start = time.time()

        # Build context from retrieved chunks
        context_parts = []
        for i, chunk in enumerate(context_chunks[:5]):
            context_parts.append(f'[Source {i+1}: {chunk["source"]}] {chunk["text"]}')
        context = '\n'.join(context_parts)

        # Create prompt
        prompt = (
            f'Answer the question based on the given context. '
            f'If the answer is not in the context, say so.\n\n'
            f'Context:\n{context}\n\n'
            f'Question: {query}\n\n'
            f'Answer:'
        )

        # Generate
        inputs = self.tokenizer(prompt, return_tensors='pt',
                                max_length=512, truncation=True)
        with torch.no_grad():
            outputs = self.model.generate(
                **inputs, max_length=max_length,
                num_beams=4, early_stopping=True,
                no_repeat_ngram_size=3
            )
        answer = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
        elapsed = time.time() - start

        result = {
            'query': query, 'answer': answer,
            'context_used': len(context_chunks),
            'sources': [c['source'] for c in context_chunks],
            'generation_time_ms': round(elapsed * 1000, 1)
        }
        self.generation_log.append(result)
        return result


generator = AnswerGenerator()
print('\n✅ Answer Generator ready!')

  🔄 Loading language model: google/flan-t5-base

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

  ✅ Language model loaded!

✅ Answer Generator ready!

## 🔗 Section 9: Complete RAG Pipeline
Connecting all components into a unified end-to-end question answering system.

In [29]:
class RAGPipeline:
    """End-to-end RAG Question Answering Pipeline."""

    def __init__(self, retriever: HybridRetriever, generator: AnswerGenerator):
        self.retriever = retriever
        self.generator = generator
        self.qa_history = []

    def ask(self, question: str, top_k: int = 5,
            method: str = 'hybrid', verbose: bool = True) -> Dict:
        """Ask a question and get a grounded answer."""
        # Step 1: Retrieve
        retrieved = self.retriever.retrieve(question, top_k=top_k, method=method)

        # Step 2: Generate
        result = self.generator.generate(question, retrieved)
        result['retrieval_method'] = method
        result['retrieved_chunks'] = retrieved

        self.qa_history.append(result)

        if verbose:
            self._display_result(result)
        return result

    def _display_result(self, result: Dict):
        html = f"""
        <div style='background:linear-gradient(135deg,#1a1a2e,#16213e);color:#fff;
                    padding:20px;border-radius:12px;margin:10px 0;
                    font-family:system-ui;border:1px solid #0f3460'>
          <h3 style='color:#e94560;margin-top:0'>❓ {result['query']}</h3>
          <div style='background:#0f3460;padding:15px;border-radius:8px;
                      margin:10px 0;border-left:4px solid #e94560'>
            <b style='color:#53d8fb'>💡 Answer:</b><br>
            <span style='font-size:1.05em'>{result['answer']}</span>
          </div>
          <div style='font-size:0.85em;color:#a0a0a0'>
            📚 Sources: {', '.join(set(result['sources'][:3]))} |
            ⏱️ {result['generation_time_ms']}ms |
            📄 {result['context_used']} chunks used
          </div>
        </div>"""
        display(HTML(html))


# Create the pipeline
rag = RAGPipeline(retriever, generator)
print('✅ RAG Pipeline assembled and ready!')

✅ RAG Pipeline assembled and ready!

## 🧪 Section 10: Validation — Testing with Dynamic Sample Questions
**Evaluator Check #1**: Operational end-to-end QA pipeline with grounded, context-aware answers.

**Evaluator Check #2**: Documented validation logs showing accurate retrieval performance.

In [30]:
# ── Test with diverse questions ──
test_questions = [
    'What is Retrieval-Augmented Generation and how does it work?',
    'What are the key stages of a RAG pipeline?',
    'How does deep learning differ from traditional machine learning?',
    'What is a vector database and why is it important for RAG?',
    'What are the advantages of hybrid search in RAG systems?',
    'What is transfer learning in NLP?',
    'How does the transformer architecture work?',
    'What is BM25 and how is it used in information retrieval?',
]

print('='*80)
print('🧪 VALIDATION: Running test questions through the RAG pipeline')
print('='*80)

for i, q in enumerate(test_questions):
    print(f'\n--- Question {i+1}/{len(test_questions)} ---')
    result = rag.ask(q, top_k=5, method='hybrid')

================================================================================
🧪 VALIDATION: Running test questions through the RAG pipeline
================================================================================

--- Question 1/8 ---

--- Question 2/8 ---

--- Question 3/8 ---

--- Question 4/8 ---

--- Question 5/8 ---

--- Question 6/8 ---

--- Question 7/8 ---

--- Question 8/8 ---

### 10.1 — Retrieval Method Comparison
Compare vector-only, BM25-only, and hybrid retrieval methods.

In [31]:
comparison_query = 'What is the role of embeddings in a RAG system?'
methods = ['vector', 'bm25', 'hybrid']

print('📊 Retrieval Method Comparison')
print(f'Query: "{comparison_query}"')
print('='*80)

for method in methods:
    print(f'\n🔍 Method: {method.upper()}')
    result = rag.ask(comparison_query, top_k=3, method=method, verbose=True)

📊 Retrieval Method Comparison
Query: "What is the role of embeddings in a RAG system?"
================================================================================

🔍 Method: VECTOR

🔍 Method: BM25

🔍 Method: HYBRID

## 📊 Section 11: System Metrics Report
**Evaluator Check #3**: System metrics report detailing chunking profiles,
embedding dimensions, vector store tools, and language model setups.

**Intern Instruction #8**: Experiment with system optimizations.

In [32]:
# ── Comprehensive System Metrics Report ──
print('='*80)
print('📊 SYSTEM METRICS REPORT')
print('='*80)

# 1. Chunking Profile
print('\n┌─────────────────────────────────────────────────┐')
print('│  📝 CHUNKING PROFILE                            │')
print('├─────────────────────────────────────────────────┤')
chunk_sizes = [c['char_count'] for c in chunks]
chunk_words = [c['word_count'] for c in chunks]
print(f'│  Strategy:        Sentence-based chunking       │')
print(f'│  Total Chunks:    {len(chunks):<30}│')
print(f'│  Avg Chunk Size:  {np.mean(chunk_sizes):.0f} characters{" "*17}│')
print(f'│  Min Chunk Size:  {min(chunk_sizes)} characters{" "*17}│')
print(f'│  Max Chunk Size:  {max(chunk_sizes)} characters{" "*16}│')
print(f'│  Avg Words/Chunk: {np.mean(chunk_words):.0f}{" "*29}│')
print('└─────────────────────────────────────────────────┘')

# 2. Embedding Profile
print('\n┌─────────────────────────────────────────────────┐')
print('│  🧮 EMBEDDING PROFILE                           │')
print('├─────────────────────────────────────────────────┤')
print(f'│  Model:      all-MiniLM-L6-v2                  │')
print(f'│  Dimensions: {embed_engine.embedding_dim}{" "*35}│')
print(f'│  Total Vectors: {embeddings.shape[0]}{" "*31}│')
print(f'│  Normalized: Yes (cosine similarity)           │')
print('└─────────────────────────────────────────────────┘')

# 3. Vector Store Profile
stats = vector_store.get_stats()
print('\n┌─────────────────────────────────────────────────┐')
print('│  🗄️  VECTOR STORE PROFILE                       │')
print('├─────────────────────────────────────────────────┤')
print(f'│  Engine:    FAISS (Facebook AI)                 │')
print(f'│  Index:     Flat Inner Product (exact search)   │')
print(f'│  Vectors:   {stats["total_vectors"]}{" "*36}│')
print(f'│  Dimension: {stats["dimension"]}{" "*34}│')
print('└─────────────────────────────────────────────────┘')

# 4. LM Profile
print('\n┌─────────────────────────────────────────────────┐')
print('│  🤖 LANGUAGE MODEL PROFILE                      │')
print('├─────────────────────────────────────────────────┤')
print(f'│  Model:     google/flan-t5-base                │')
print(f'│  Type:      Seq2Seq (encoder-decoder)          │')
print(f'│  Decoding:  Beam search (num_beams=4)          │')
print(f'│  Max Len:   256 tokens                         │')
print('└─────────────────────────────────────────────────┘')

# 5. Retrieval Profile
print('\n┌─────────────────────────────────────────────────┐')
print('│  🔍 RETRIEVAL PROFILE                           │')
print('├─────────────────────────────────────────────────┤')
print(f'│  Mode:      Hybrid (Vector + BM25 + Reranking) │')
print(f'│  Reranker:  cross-encoder/ms-marco-MiniLM-L-6  │')
print(f'│  Fusion:    Reciprocal Rank Fusion (alpha=0.7) │')
print(f'│  Top-K:     5 chunks per query                 │')
print('└─────────────────────────────────────────────────┘')

================================================================================
📊 SYSTEM METRICS REPORT
================================================================================

┌─────────────────────────────────────────────────┐
│  📝 CHUNKING PROFILE                            │
├─────────────────────────────────────────────────┤
│  Strategy:        Sentence-based chunking       │
│  Total Chunks:    20                            │
│  Avg Chunk Size:  596 characters                 │
│  Min Chunk Size:  366 characters                 │
│  Max Chunk Size:  1130 characters                │
│  Avg Words/Chunk: 81                             │
└─────────────────────────────────────────────────┘

┌─────────────────────────────────────────────────┐
│  🧮 EMBEDDING PROFILE                           │
├─────────────────────────────────────────────────┤
│  Model:      all-MiniLM-L6-v2                  │
│  Dimensions: 384                                   │
│  Total Vectors: 20                               │
│  Normalized: Yes (cosine similarity)           │
└─────────────────────────────────────────────────┘

┌─────────────────────────────────────────────────┐
│  🗄️  VECTOR STORE PROFILE                       │
├─────────────────────────────────────────────────┤
│  Engine:    FAISS (Facebook AI)                 │
│  Index:     Flat Inner Product (exact search)   │
│  Vectors:   20                                    │
│  Dimension: 384                                  │
└─────────────────────────────────────────────────┘

┌─────────────────────────────────────────────────┐
│  🤖 LANGUAGE MODEL PROFILE                      │
├─────────────────────────────────────────────────┤
│  Model:     google/flan-t5-base                │
│  Type:      Seq2Seq (encoder-decoder)          │
│  Decoding:  Beam search (num_beams=4)          │
│  Max Len:   256 tokens                         │
└─────────────────────────────────────────────────┘

┌─────────────────────────────────────────────────┐
│  🔍 RETRIEVAL PROFILE                           │
├─────────────────────────────────────────────────┤
│  Mode:      Hybrid (Vector + BM25 + Reranking) │
│  Reranker:  cross-encoder/ms-marco-MiniLM-L-6  │
│  Fusion:    Reciprocal Rank Fusion (alpha=0.7) │
│  Top-K:     5 chunks per query                 │
└─────────────────────────────────────────────────┘

### 11.1 — Chunk Size Distribution Visualization

In [33]:
# ── Chunk size distribution plot ──
fig = go.Figure()
fig.add_trace(go.Histogram(
    x=chunk_sizes, nbinsx=20,
    marker_color='#e94560', opacity=0.8,
    name='Character Count'
))
fig.update_layout(
    title='📊 Chunk Size Distribution',
    xaxis_title='Characters per Chunk',
    yaxis_title='Frequency',
    template='plotly_dark',
    width=700, height=400
)
fig.show()

# ── Source distribution ──
source_counts = pd.Series([c['source'] for c in chunks]).value_counts()
fig2 = go.Figure(go.Bar(
    x=source_counts.values, y=source_counts.index,
    orientation='h', marker_color='#53d8fb'
))
fig2.update_layout(
    title='📚 Chunks per Source Document',
    xaxis_title='Number of Chunks',
    template='plotly_dark',
    width=700, height=350
)
fig2.show()

### 11.2 — Retrieval Performance Log

In [34]:
# Show retrieval performance log
if retriever.retrieval_log:
    log_df = pd.DataFrame(retriever.retrieval_log)
    print('📋 Retrieval Performance Log:')
    display(log_df)

    fig3 = go.Figure(go.Bar(
        x=log_df.index,
        y=log_df['time_ms'],
        marker_color=log_df['method'].map(
            {'vector':'#e94560','bm25':'#53d8fb','hybrid':'#ffd700'}
        ),
        text=log_df['method'],
        textposition='outside'
    ))
    fig3.update_layout(
        title='⏱️ Retrieval Latency per Query',
        xaxis_title='Query Index',
        yaxis_title='Time (ms)',
        template='plotly_dark',
        width=700, height=400
    )
    fig3.show()

📋 Retrieval Performance Log:

,query,method,results,time_ms
0,What is Retrieval-Augmented Generation and how...,hybrid,5,2896.6
1,What are the key stages of a RAG pipeline?,hybrid,5,2589.7
2,How does deep learning differ from traditional...,hybrid,5,1761.4
3,What is a vector database and why is it import...,hybrid,5,3814.3
4,What are the advantages of hybrid search in RA...,hybrid,5,2733.5
5,What is transfer learning in NLP?,hybrid,5,2448.5
6,How does the transformer architecture work?,hybrid,5,2560.0
7,What is BM25 and how is it used in information...,hybrid,5,3640.9
8,What is the role of embeddings in a RAG system?,vector,3,1625.1
9,What is the role of embeddings in a RAG system?,bm25,3,706.5
10,What is the role of embeddings in a RAG system?,hybrid,3,1492.3

### 11.3 — QA History & Generation Log

In [35]:
# Display full QA history
qa_df = pd.DataFrame([{
    'Question': r['query'][:60] + '...' if len(r['query'])>60 else r['query'],
    'Answer': r['answer'][:80] + '...' if len(r['answer'])>80 else r['answer'],
    'Sources': ', '.join(set(r['sources'][:2])),
    'Gen Time (ms)': r['generation_time_ms'],
    'Chunks Used': r['context_used']
} for r in rag.qa_history])

print('📋 Complete QA History:')
display(qa_df.style.set_properties(**{
    'background-color': '#1a1a2e', 'color': 'white',
    'border-color': '#0f3460'
}))

📋 Complete QA History:

## Example Flow
**User Question:** "What is the main idea of the document?"

**System Process:**
* Retrieves relevant sections from ingested documents
* Provides them as context to the language model
* Generates a concise, grounded answer

In [36]:
# ── Example Flow: "What is the main idea of the document?" ──
print('Example Flow Demonstration')
print('='*60)
example_result = rag.ask(
    'What is the main idea of the document?',
    top_k=5, method='hybrid'
)

Example Flow Demonstration
============================================================

## 🎨 Section 12: Interactive UI with Gradio
A beautiful, interactive interface for the RAG system.

In [39]:

import gradio as gr
import easyocr
import os

# Create OCR reader once (lazy initialization to avoid loading if not used)
_ocr_reader = None
def get_ocr_reader():
    global _ocr_reader
    if _ocr_reader is None:
        _ocr_reader = easyocr.Reader(['en'])
    return _ocr_reader

def process_files(files):
    if not files:
        return "⚠️ No files uploaded.", gr.update(choices=[], value=None)
    
    new_docs = []
    for f in files:
        ext = f.name.lower().split('.')[-1]
        basename = os.path.basename(f.name)
        if ext == 'pdf':
            doc = ingester.ingest_pdf(f.name)
        elif ext in ['txt', 'md']:
            doc = ingester.ingest_txt_file(f.name)
        elif ext in ['png', 'jpg', 'jpeg']:
            reader = get_ocr_reader()
            results = reader.readtext(f.name)
            text = " ".join([res[1] for res in results])
            doc = ingester.ingest_text(text, source=basename)
        else:
            continue
        new_docs.append(doc)
        
    if not new_docs:
        return "⚠️ No valid documents processed (supported: PDF, TXT, PNG, JPG).", gr.update()
        
    # Chunk new docs
    new_chunks = chunker.chunk_documents(new_docs, strategy='sentence')
    global chunks
    chunks.extend(new_chunks)
    
    # Embed new chunks
    new_chunk_texts = [c['text'] for c in new_chunks]
    new_embs = embed_engine.embed_texts(new_chunk_texts, show_progress=False)
    
    # Add to vector store
    vector_store.add(new_embs, new_chunks)
    
    # Re-initialize Retriever
    global retriever
    retriever = HybridRetriever(vector_store, embed_engine, chunks, use_reranker=True)
    rag.retriever = retriever
    
    source_names = [d.source for d in new_docs]
    doc_list = ", ".join(source_names)
    
    return f"✅ Successfully processed {len(new_docs)} files and added {len(new_chunks)} chunks to the RAG database.\nFiles: {doc_list}"

def answer_question(question, retrieval_method, top_k):
    """Process a question through the RAG pipeline."""
    if not question.strip():
        return 'Please enter a question.', '', ''

    top_k = int(top_k)
    result = rag.ask(question, top_k=top_k, method=retrieval_method, verbose=False)

    answer = result['answer']

    # Format retrieved sources
    sources_text = ''
    for i, chunk in enumerate(result.get('retrieved_chunks', [])[:3]):
        score = chunk.get('rerank_score', chunk.get('similarity_score', 0))
        sources_text += f'**[Source {i+1}]** {chunk["source"]} (score: {score:.3f})\n'
        sources_text += f'> {chunk["text"][:200]}...\n\n'

    # Metrics
    metrics = (
        f'⏱️ Generation Time: {result["generation_time_ms"]}ms | '
        f'📄 Chunks Used: {result["context_used"]} | '
        f'🔍 Method: {retrieval_method}'
    )
    return answer, sources_text, metrics

# CSS matching the Lumina / Architect UI Aesthetic
custom_css = """
.gradio-container {
    background-color: #f8f9ff !important;
    font-family: 'Inter', sans-serif !important;
    color: #0b1c30 !important;
}
.gr-button-primary {
    background: linear-gradient(135deg, #0041a2 0%, #0856cf 100%) !important;
    border: none !important;
    color: white !important;
    border-radius: 8px !important;
    font-weight: 600 !important;
}
.gr-box, .gr-panel, .gr-file {
    background-color: #ffffff !important;
    border: 1px solid #c3c6d6 !important;
    border-radius: 12px !important;
    box-shadow: 0 2px 4px rgba(0,0,0,0.02) !important;
}
.header-bar {
    background-color: #ffffff;
    border-bottom: 1px solid #c3c6d6;
    padding: 15px 20px;
    border-radius: 12px 12px 0 0;
    margin-bottom: 20px;
    display: flex;
    align-items: center;
}
.header-icon {
    color: #0041a2;
    margin-right: 10px;
    font-size: 24px;
}
.header-title {
    color: #0041a2;
    font-weight: 600;
    font-size: 1.25rem;
    margin: 0;
}
h1, h2, h3 {
    color: #0b1c30 !important;
}
"""

# Build Gradio Interface
with gr.Blocks(css=custom_css, theme=gr.themes.Soft()) as demo:
    gr.HTML("""
    <div class="header-bar">
        <span class="header-icon">❖</span>
        <h1 class="header-title">RAG-Architect Dashboard</h1>
    </div>
    """)
    
    with gr.Row():
        # Left Column: Upload & Settings
        with gr.Column(scale=1):
            gr.Markdown("### 📂 Data Source Management")
            file_uploader = gr.File(
                label="Upload Custom Documents (PDF, TXT, PNG, JPG)",
                file_count="multiple",
                file_types=[".pdf", ".txt", ".md", ".png", ".jpg", ".jpeg"]
            )
            upload_btn = gr.Button("Processing Uploads", variant="secondary")
            upload_status = gr.Textbox(label="Status", interactive=False)
            
            gr.Markdown("### ⚙️ Pipeline Settings")
            method_select = gr.Dropdown(
                choices=['hybrid', 'vector', 'bm25'],
                value='hybrid', label='🔍 Retrieval Method'
            )
            topk_slider = gr.Slider(
                minimum=1, maximum=10, value=5, step=1,
                label='📄 Top-K Chunks'
            )
            
        # Right Column: Chat/Q&A
        with gr.Column(scale=2):
            gr.Markdown("### 💬 Knowledge Assistant")
            question_input = gr.Textbox(
                label='❓ Your Question',
                placeholder='Ask anything about the ingested documents...',
                lines=3
            )
            ask_btn = gr.Button('🚀 Generate Answer', variant='primary', size='lg')
            
            with gr.Row():
                answer_output = gr.Textbox(label='💡 Answer', lines=5, interactive=False)
            
            with gr.Accordion("Retrieved Context & Metrics", open=False):
                metrics_output = gr.Textbox(label='📊 Metrics', interactive=False)
                sources_output = gr.Markdown(label='📚 Retrieved Sources')

    # Events
    upload_btn.click(
        fn=process_files,
        inputs=[file_uploader],
        outputs=[upload_status]
    )

    ask_btn.click(
        fn=answer_question,
        inputs=[question_input, method_select, topk_slider],
        outputs=[answer_output, sources_output, metrics_output]
    )

# Launch the UI
demo.launch(share=True, inline=True)

* Running on local URL:  http://127.0.0.1:7862

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

## Improvements & Experiments
**Intern Instruction #8**: Experiment with system optimizations.

The following experiments were explored in this project:
* **Better chunking strategies**: Sentence-based, character-based, and paragraph-based chunking
* **Different embedding models**: Using `all-MiniLM-L6-v2` (384-dim, fast & efficient)
* **Hybrid search**: Combined keyword (BM25) + vector (FAISS) retrieval with Reciprocal Rank Fusion
* **Re-ranking**: Cross-encoder (`ms-marco-MiniLM-L-6-v2`) for better relevance scoring
* **Different language models**: Using `google/flan-t5-base` for grounded generation

In [38]:
# ── Chunking Strategy Comparison ──
print('Chunking Strategy Comparison')
print('='*60)
sample_text = ingester.documents[0].content
test_chunker = TextChunker(chunk_size=300, chunk_overlap=50)

strategies = {
    'sentence': test_chunker.chunk_by_sentences(sample_text),
    'character': test_chunker.chunk_by_characters(sample_text),
    'paragraph': test_chunker.chunk_by_paragraphs(sample_text),
}

comparison_data = []
for name, ch in strategies.items():
    sizes = [len(c) for c in ch]
    comparison_data.append({
        'Strategy': name,
        'Num Chunks': len(ch),
        'Avg Size (chars)': int(np.mean(sizes)) if sizes else 0,
        'Min Size': min(sizes) if sizes else 0,
        'Max Size': max(sizes) if sizes else 0,
    })

comp_df = pd.DataFrame(comparison_data)
print('\nChunking Strategy Results:')
display(comp_df)

# Visualize
fig = go.Figure()
for name, ch in strategies.items():
    fig.add_trace(go.Box(y=[len(c) for c in ch], name=name,
                         boxmean=True))
fig.update_layout(
    title='Chunk Size Distribution by Strategy',
    yaxis_title='Characters per Chunk',
    template='plotly_dark', width=700, height=400
)
fig.show()

Chunking Strategy Comparison
============================================================

Chunking Strategy Results:

    Strategy  Num Chunks  Avg Size (chars)  Min Size  Max Size
0   sentence           6               595       460       756
1  character          13               270        10       299
2  paragraph           8               368       264       457

## 📝 Section 13: Key Learnings & Conclusion

### Key Learnings
1. **RAG Architecture**: Understood how retrieval and generation work together
2. **Embeddings**: Learned how text is converted to vector representations
3. **Vector Databases**: Used FAISS for efficient similarity search
4. **Hybrid Search**: Combined BM25 keyword search with dense vector search
5. **Re-ranking**: Applied cross-encoder re-ranking for better precision
6. **Text Chunking**: Explored sentence-based, character-based, and paragraph strategies

### System Summary
| Component | Implementation |
|-----------|---------------|
| Document Ingestion | PDF, TXT, Raw Text, HuggingFace datasets |
| Chunking | Sentence-based (configurable) |
| Embedding | `all-MiniLM-L6-v2` (384 dimensions) |
| Vector Store | FAISS (Flat Inner Product) |
| Retrieval | Hybrid (Vector + BM25 + Re-ranking) |
| Generation | `google/flan-t5-base` (Seq2Seq) |
| Re-ranking | `cross-encoder/ms-marco-MiniLM-L-6-v2` |
| UI | Gradio Interactive Interface |

### Conclusion
This project demonstrates a complete, production-grade RAG system capable of:
- Ingesting multiple document formats
- Efficiently chunking and embedding text
- Performing hybrid retrieval with re-ranking
- Generating grounded, context-aware answers
- Providing an interactive UI for end-user interaction

RAG systems are the foundation of modern AI assistants, enterprise search, and knowledge management tools.

---
**Umang Vijay | JECRC University | Celebal CEI Data Science Internship — Week 7**